name: Print Software Versions

on:
  push:
    branches:
      - master

jobs:
  # Перша робота: Обробка даних
  print-app-server-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS version
        run: uname -a
      - name: Print Apache Tomcat version
        run: |
          echo "Apache Tomcat Version:"
          # Перевірка на наявність curl
          if ! command -v curl &> /dev/null
          then
              echo "curl not found, installing..."
              sudo apt-get update && sudo apt-get install -y curl
          fi
          # Якщо curl встановлений, використовуємо його для перевірки Tomcat
          curl -s http://localhost:8080/ | grep "Apache Tomcat"

  # Друга робота: Доступ до даних
  print-db-server-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS version
        run: uname -a
      - name: Print PostgreSQL version
        run: psql --version


