name: Print Software Versions

on:
  push:
    branches:
      - master

jobs:
  # Перша робота: Обробка даних
  print-app-server-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS version
        run: uname -a
      - name: Print Apache Tomcat version
        run: |
          echo "Apache Tomcat Version:"
          apt-get update && apt-get install -y curl
          curl -s http://localhost:8080/ | grep "Apache Tomcat"

  # Друга робота: Доступ до даних
  print-db-server-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS version
        run: uname -a
      - name: Print PostgreSQL version
        run: psql --version
