name: Print Software Versions

on:
  push:
    branches:
      - master

jobs:
  # Перша робота: Обробка даних
  print-app-server-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS version
        run: uname -a
      - name: Check Apache Tomcat installation
        run: |
          echo "Checking for Apache Tomcat installation:"
          if command -v tomcat7 >/dev/null 2>&1; then
            tomcat7 -v
          elif command -v tomcat8 >/dev/null 2>&1; then
            tomcat8 -v
          else
            echo "Apache Tomcat is not installed."
          fi

  # Друга робота: Доступ до даних
  print-db-server-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS version
        run: uname -a
      - name: Print PostgreSQL version
        run: psql --version


