name: Data Schema Code Convention Check

on:
  push:
    branches:
      - master

jobs:
  check-sql-code-conventions:
    runs-on: ubuntu-latest

    steps:
      # Крок для перевірки кодування схеми даних
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sqlfluff
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff

      - name: Check DataSchema.sql for code conventions
        run: |
          if [ -f "DataSchema.sql" ]; then
            echo "Checking SQL file for code conventions"
            # Вказуємо діалект PostgreSQL
            sqlfluff lint --dialect postgres DataSchema.sql
          else
            echo "No DataSchema.sql file found!"
            exit 1
          fi
