name: Print Software Versions

on:
  push:
    branches:
      - master

jobs:
  # Перша робота: Обробка даних
  print-app-server-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS version
        run: uname -a
      - name: Print Apache Tomcat version
        run: |
          echo "Apache Tomcat Version:"
          # Перевірка версії Tomcat за допомогою команди dpkg
          dpkg-query -l | grep tomcat

  # Друга робота: Доступ до даних
  print-db-server-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS version
        run: uname -a
      - name: Print PostgreSQL version
        run: psql --version


